apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}
data:
  DB_URL: {{ printf "jdbc:postgresql://%s:%d/%s" .Values.db.host (int .Values.db.port) .Values.db.name | quote }}